/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Tue Jun  2 19:33:51 2015. */

#include "controller_state.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ControllerState_fields[23] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ControllerState, controller_id, controller_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bdl, controller_id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bdr, bdl, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bdu, bdr, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bdd, bdu, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, ba, bdd, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bb, ba, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bx, bb, 0),
    PB_FIELD(  9, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, by, bx, 0),
    PB_FIELD( 10, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bl, by, 0),
    PB_FIELD( 11, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, br, bl, 0),
    PB_FIELD( 12, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bm, br, 0),
    PB_FIELD( 13, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bp, bm, 0),
    PB_FIELD( 14, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bhome, bp, 0),
    PB_FIELD( 15, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bzl, bhome, 0),
    PB_FIELD( 16, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, bzr, bzl, 0),
    PB_FIELD( 17, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, lt, bzr, 0),
    PB_FIELD( 18, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, rt, lt, 0),
    PB_FIELD( 19, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, lx, rt, 0),
    PB_FIELD( 20, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, ly, lx, 0),
    PB_FIELD( 21, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, rx, ly, 0),
    PB_FIELD( 22, INT32   , REQUIRED, STATIC  , OTHER, ControllerState, ry, rx, 0),
    PB_LAST_FIELD
};


