# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller_state.proto',
  package='',
  serialized_pb=_b('\n\x16\x63ontroller_state.proto\"\xad\x02\n\x0f\x43ontrollerState\x12\x15\n\rcontroller_id\x18\x01 \x02(\x05\x12\x0b\n\x03\x62\x64l\x18\x02 \x02(\x05\x12\x0b\n\x03\x62\x64r\x18\x03 \x02(\x05\x12\x0b\n\x03\x62\x64u\x18\x04 \x02(\x05\x12\x0b\n\x03\x62\x64\x64\x18\x05 \x02(\x05\x12\n\n\x02\x62\x61\x18\x06 \x02(\x05\x12\n\n\x02\x62\x62\x18\x07 \x02(\x05\x12\n\n\x02\x62x\x18\x08 \x02(\x05\x12\n\n\x02\x62y\x18\t \x02(\x05\x12\n\n\x02\x62l\x18\n \x02(\x05\x12\n\n\x02\x62r\x18\x0b \x02(\x05\x12\n\n\x02\x62m\x18\x0c \x02(\x05\x12\n\n\x02\x62p\x18\r \x02(\x05\x12\r\n\x05\x62home\x18\x0e \x02(\x05\x12\x0b\n\x03\x62zl\x18\x0f \x02(\x05\x12\x0b\n\x03\x62zr\x18\x10 \x02(\x05\x12\n\n\x02lt\x18\x11 \x02(\x05\x12\n\n\x02rt\x18\x12 \x02(\x05\x12\n\n\x02lx\x18\x13 \x02(\x05\x12\n\n\x02ly\x18\x14 \x02(\x05\x12\n\n\x02rx\x18\x15 \x02(\x05\x12\n\n\x02ry\x18\x16 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTROLLERSTATE = _descriptor.Descriptor(
  name='ControllerState',
  full_name='ControllerState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='controller_id', full_name='ControllerState.controller_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bdl', full_name='ControllerState.bdl', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bdr', full_name='ControllerState.bdr', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bdu', full_name='ControllerState.bdu', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bdd', full_name='ControllerState.bdd', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ba', full_name='ControllerState.ba', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bb', full_name='ControllerState.bb', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bx', full_name='ControllerState.bx', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='by', full_name='ControllerState.by', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bl', full_name='ControllerState.bl', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='br', full_name='ControllerState.br', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bm', full_name='ControllerState.bm', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bp', full_name='ControllerState.bp', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bhome', full_name='ControllerState.bhome', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bzl', full_name='ControllerState.bzl', index=14,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bzr', full_name='ControllerState.bzr', index=15,
      number=16, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lt', full_name='ControllerState.lt', index=16,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rt', full_name='ControllerState.rt', index=17,
      number=18, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lx', full_name='ControllerState.lx', index=18,
      number=19, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ly', full_name='ControllerState.ly', index=19,
      number=20, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx', full_name='ControllerState.rx', index=20,
      number=21, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ry', full_name='ControllerState.ry', index=21,
      number=22, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=328,
)

DESCRIPTOR.message_types_by_name['ControllerState'] = _CONTROLLERSTATE

ControllerState = _reflection.GeneratedProtocolMessageType('ControllerState', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERSTATE,
  __module__ = 'controller_state_pb2'
  # @@protoc_insertion_point(class_scope:ControllerState)
  ))
_sym_db.RegisterMessage(ControllerState)


# @@protoc_insertion_point(module_scope)
